# Generated by Django 4.2.4 on 2023-09-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='webhook',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='invite_link',
        ),
        migrations.AlterField(
            model_name='bot',
            name='token',
            field=models.CharField(help_text='Create a Telegram bot using @BotFather and copy the received token into this field.<br>Token example: 0123456789:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX<br><br>Create a Discord bot using Developers > Applications > New Application.<br>Token example: XXXXXXXXXXXXXXXXXXXXXXXXXX.XXXXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', max_length=255, verbose_name='Bot token'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='title',
            field=models.CharField(blank=True, help_text='Name retrieved automatically via API', max_length=255, null=True, verbose_name='Channel title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='document',
            field=models.FileField(blank=True, help_text='Select a document file to send', null=True, upload_to='', verbose_name='Document file'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, help_text='Select a photo file to send', null=True, upload_to='', verbose_name='Photo file'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, help_text='Select a video file to send', null=True, upload_to='', verbose_name='Video file'),
        ),
        migrations.AlterField(
            model_name='post',
            name='voice',
            field=models.FileField(blank=True, help_text='Select a audio file to send', null=True, upload_to='', verbose_name='Voice file'),
        ),
    ]
