# Generated by Django 4.2.4 on 2023-09-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'ordering': ['-created_at'], 'verbose_name': 'Channel', 'verbose_name_plural': 'Channels'},
        ),
        migrations.AddField(
            model_name='bot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='channel_id',
            field=models.BigIntegerField(help_text='', verbose_name='Telegram channel id'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='description',
            field=models.CharField(blank=True, help_text='', null=True, verbose_name='Telegram channel description'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='invite_link',
            field=models.CharField(blank=True, help_text='', null=True, verbose_name='Telegram channel invite link'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='title',
            field=models.CharField(blank=True, help_text='', max_length=255, null=True, verbose_name='Telegram channel name'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='username',
            field=models.CharField(blank=True, help_text='', null=True, verbose_name='Telegram channel username'),
        ),
        migrations.AlterField(
            model_name='post',
            name='document',
            field=models.FileField(blank=True, help_text='', null=True, upload_to='', verbose_name='Document file'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, help_text='', null=True, upload_to='', verbose_name='Photo file'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, help_text='', null=True, upload_to='', verbose_name='Video file'),
        ),
        migrations.AlterField(
            model_name='post',
            name='voice',
            field=models.FileField(blank=True, help_text='', null=True, upload_to='', verbose_name='Voice file'),
        ),
        migrations.AlterField(
            model_name='record',
            name='record_type',
            field=models.CharField(choices=[('create', 'CREATE'), ('update', 'UPDATE'), ('delete', 'DELETE')], help_text='Type of action at which the record was created', max_length=32, null=True, verbose_name='Record type'),
        ),
    ]
