# Generated by Django 4.2.4 on 2023-09-09 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0002_alter_channel_options_bot_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Date of update')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date of creation')),
                ('task_id', models.UUIDField(verbose_name='Celery task id')),
                ('task_type', models.CharField(choices=[('create', 'CREATE'), ('update', 'UPDATE'), ('delete', 'DELETE')], help_text='Type of action at which the record was created', max_length=32, null=True, verbose_name='Task type')),
                ('response', models.TextField(help_text='Automatically recorded result of sending a message', null=True, verbose_name='Response data')),
                ('exception', models.TextField(help_text='Automatically detected exception to sending a message', null=True, verbose_name='Exception data')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='channel',
            name='channel_id',
            field=models.BigIntegerField(help_text='', verbose_name='Telegram channel id'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='description',
            field=models.CharField(blank=True, help_text='', null=True, verbose_name='Telegram channel description'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='invite_link',
            field=models.CharField(blank=True, help_text='', null=True, verbose_name='Telegram channel invite link'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='title',
            field=models.CharField(blank=True, help_text='', max_length=255, null=True, verbose_name='Telegram channel name'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='username',
            field=models.CharField(blank=True, help_text='', null=True, verbose_name='Telegram channel username'),
        ),
        migrations.AlterField(
            model_name='post',
            name='document',
            field=models.FileField(blank=True, help_text='', null=True, upload_to='', verbose_name='Document file'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, help_text='', null=True, upload_to='', verbose_name='Photo file'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, help_text='', null=True, upload_to='', verbose_name='Video file'),
        ),
        migrations.AlterField(
            model_name='post',
            name='voice',
            field=models.FileField(blank=True, help_text='', null=True, upload_to='', verbose_name='Voice file'),
        ),
        migrations.DeleteModel(
            name='Record',
        ),
        migrations.AddField(
            model_name='task',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='poster.channel', verbose_name='Channel'),
        ),
        migrations.AddField(
            model_name='task',
            name='post',
            field=models.ForeignKey(help_text='Original post', null=True, on_delete=django.db.models.deletion.SET_NULL, to='poster.post', verbose_name='Post'),
        ),
    ]
