# Generated by Django 4.2.4 on 2023-09-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0002_remove_bot_webhook_remove_channel_invite_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_silent',
            field=models.BooleanField(default=False, verbose_name='Is silent'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='server_id',
            field=models.BigIntegerField(blank=True, help_text='Server (Guild) id retrieved automatically via API', null=True, verbose_name='Discord server id'),
        ),
    ]
