# Generated by Django 4.2.4 on 2023-09-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0003_task_alter_channel_channel_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AddField(
            model_name='channel',
            name='channel_type',
            field=models.CharField(choices=[('discord', 'Discord'), ('telegram', 'Telegram')], default='telegram', help_text='', max_length=255, verbose_name='Telegram channel id'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='channel_id',
            field=models.BigIntegerField(help_text='', verbose_name='Telegram channel id'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='description',
            field=models.CharField(blank=True, help_text='', null=True, verbose_name='Telegram channel description'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='invite_link',
            field=models.CharField(blank=True, help_text='', null=True, verbose_name='Telegram channel invite link'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='title',
            field=models.CharField(blank=True, help_text='', max_length=255, null=True, verbose_name='Telegram channel name'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='username',
            field=models.CharField(blank=True, help_text='', null=True, verbose_name='Telegram channel username'),
        ),
        migrations.AlterField(
            model_name='post',
            name='document',
            field=models.FileField(blank=True, help_text='', null=True, upload_to='', verbose_name='Document file'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, help_text='', null=True, upload_to='', verbose_name='Photo file'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, help_text='', null=True, upload_to='', verbose_name='Video file'),
        ),
        migrations.AlterField(
            model_name='post',
            name='voice',
            field=models.FileField(blank=True, help_text='', null=True, upload_to='', verbose_name='Voice file'),
        ),
    ]
