# Generated by Django 4.2.4 on 2023-09-12 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0004_alter_post_options_channel_channel_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmessage',
            name='channel_id',
        ),
        migrations.RemoveField(
            model_name='postmessage',
            name='channel_username',
        ),
        migrations.AddField(
            model_name='postmessage',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='poster.channel', verbose_name='Channel'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='bot',
            field=models.ForeignKey(help_text='Select the previously created Telegram bot that you added to the Telegram channel as an administrator', null=True, on_delete=django.db.models.deletion.SET_NULL, to='poster.bot', verbose_name='Bot'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='channel_id',
            field=models.BigIntegerField(help_text='Insert your channel id', verbose_name='Channel id'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='channel_type',
            field=models.CharField(choices=[('discord', 'Discord'), ('telegram', 'Telegram')], default='telegram', help_text='Available: Discord; Telegram', max_length=255, verbose_name='Channel type'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='description',
            field=models.CharField(blank=True, help_text='Description retrieved automatically via API', null=True, verbose_name='Channel description'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='invite_link',
            field=models.CharField(blank=True, help_text='Link retrieved automatically via API', null=True, verbose_name='Channel link'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='title',
            field=models.CharField(blank=True, help_text='Name retrieved automatically via API', max_length=255, null=True, verbose_name='Channel name'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='username',
            field=models.CharField(blank=True, help_text='Username retrieved automatically via API', null=True, verbose_name='Channel username'),
        ),
        migrations.AlterField(
            model_name='post',
            name='document',
            field=models.FileField(blank=True, help_text='', null=True, upload_to='', verbose_name='Document file'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, help_text='', null=True, upload_to='', verbose_name='Photo file'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, help_text='', null=True, upload_to='', verbose_name='Video file'),
        ),
        migrations.AlterField(
            model_name='post',
            name='voice',
            field=models.FileField(blank=True, help_text='', null=True, upload_to='', verbose_name='Voice file'),
        ),
    ]
