# Generated by Django 4.2.4 on 2023-09-13 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0005_remove_postmessage_channel_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='discord_server_id',
            field=models.BigIntegerField(blank=True, help_text='Insert your discord server id', null=True, verbose_name='Discord server id'),
        ),
        migrations.AddField(
            model_name='channel',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Is completed'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='channel_id',
            field=models.BigIntegerField(blank=True, help_text='Insert your channel id', null=True, verbose_name='Channel id'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='channel_type',
            field=models.CharField(choices=[('discord', 'Discord'), ('telegram', 'Telegram')], help_text='Available: Discord; Telegram', max_length=255, verbose_name='Channel type'),
        ),
        migrations.AlterField(
            model_name='post',
            name='document',
            field=models.FileField(blank=True, help_text='', null=True, upload_to='', verbose_name='Document file'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, help_text='', null=True, upload_to='', verbose_name='Photo file'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, help_text='', null=True, upload_to='', verbose_name='Video file'),
        ),
        migrations.AlterField(
            model_name='post',
            name='voice',
            field=models.FileField(blank=True, help_text='', null=True, upload_to='', verbose_name='Voice file'),
        ),
    ]
