# Generated by Django 4.2.4 on 2023-09-14 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0006_channel_discord_server_id_channel_is_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='bot_type',
            field=models.CharField(choices=[('discord_bot', 'Discord bot'), ('telegram_bot', 'Telegram bot')], default='telegram_bot', help_text='Available: Discord bot; Telegram bot', max_length=255, verbose_name='Bot type'),
        ),
        migrations.AddField(
            model_name='bot',
            name='webhook',
            field=models.CharField(blank=True, help_text='Create a Discord webhook using Server Settings > Integrations > Webhooks.<br>Webhook example: https://discord.com/api/webhooks/your-webhook-id/your-webhook-token', max_length=255, null=True, verbose_name='Discord webhook'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bot first name'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='token',
            field=models.CharField(blank=True, help_text='Create a Telegram bot using @BotFather and copy the received token into this field.<br>Token example: 0123456789:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', max_length=255, null=True, verbose_name='Telegram bot token'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bot username'),
        ),
        migrations.AlterField(
            model_name='post',
            name='document',
            field=models.FileField(blank=True, help_text='', null=True, upload_to='', verbose_name='Document file'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, help_text='', null=True, upload_to='', verbose_name='Photo file'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, help_text='', null=True, upload_to='', verbose_name='Video file'),
        ),
        migrations.AlterField(
            model_name='post',
            name='voice',
            field=models.FileField(blank=True, help_text='', null=True, upload_to='', verbose_name='Voice file'),
        ),
    ]
